CREATE TABLE t_patient
(
    t_patient_id int(11) NOT NULL AUTO_INCREMENT,
    patient_hn varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    f_patient_prefix_id int(11) DEFAULT NULL,
    patient_firstname varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_lastname varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_xn varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    f_sex_id varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_birthday varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_house varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_road varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_moo varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_tambon varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_amphur varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_changwat varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    f_patient_marriage_status_id int(11) DEFAULT NULL,
    f_patient_occupation_id int(11) DEFAULT NULL,
    f_patient_race_id varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    f_patient_nation_id varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    f_patient_religion_id int(11) DEFAULT NULL,
    f_patient_education_type_id int(11) DEFAULT NULL,
    f_patient_family_status_id int(11) DEFAULT NULL,
    patient_father_firstname varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_mother_firstname varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_couple_firstname varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_move_in_date_time varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    f_patient_discharge_status_id int(11) DEFAULT NULL,
    patient_discharge_date_time varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    f_patient_blood_group_id int(11) DEFAULT NULL,
    f_patient_foreigner_id int(11) DEFAULT NULL,
    f_patient_area_status_id int(11) DEFAULT NULL,
    patient_father_pid varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_mather_pid varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_couple_pid varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_community_status varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_private_doctor varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_pid varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_mother_lastname varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_father_lastname varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_couple_lastname varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_phone_number varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    f_patient_relation_id int(11) DEFAULT NULL,
    patient_contact_phone_number varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_contact_sex_id int(11) DEFAULT NULL,
    patient_contact_house varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_contact_moo varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_contact_changwat varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_contact_amphur varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_contact_tambon varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_contact_road varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_contact_firstname varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_contact_lastname varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_birthday_true varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_merged varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_record_date_time varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_update_date_time varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_staff_record varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_staff_modify varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_staff_cancel varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_active varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_drugallergy varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    patient_language_for_print varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL ,
    patient_patient_mobile_phone varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL ,
    patient_contact_mobile_phone varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL ,
    patient_has_home_in_pcu varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL ,
    t_health_family_id int(11) DEFAULT NULL,
    patient_other_country_address varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL ,
    patient_is_other_country varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL ,
    contact_id int(11) DEFAULT NULL,
    contact_namet varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL ,
    remark1 varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL ,
    remark2 varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL ,
    contact_join_id int(11) DEFAULT NULL,
    contact_join_namet varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL ,
    ss_patient_hn character varying COLLATE pg_catalog."default",
    patient_soi varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL ,
    patient_contact_soi varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL ,
    status_chronic varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL ,
    status_hiv varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL ,
    patient_status_hiv varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL ,
    deny_allergy varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL ,
    latitude DECIMAL(17,2),
    longitude DECIMAL(17,2),
    t_person_id varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL ,
    patient_patient_email varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL ,
    patient_contact_email varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL ,
    picture_profile varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
    PRIMARY KEY (`t_patient`)
)ENGINE=MyISAM AUTO_INCREMENT=2080000001 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='id=208';